import React, { useRef, useState } from 'react';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Body, Label, Notice } from './ui';
import { Voice } from './Voice';
import { Room } from '@/src/types';
import { RoomAction } from './Lobby';
import { makeStyles, useTheme } from '@/src/theme';
import { useApp } from '@/src/context';

export function Chat({ room, act }: { room: Room; act: RoomAction }) {
  const s = useStyles(), { colors: c } = useTheme(), { user } = useApp(), [tab, setTab] = useState('text'), [message, setMessage] = useState(''), [sending, setSending] = useState(false), scroll = useRef<ScrollView>(null);
  const send = async () => { if (!message.trim() || sending) return; setSending(true); if (await act({ type: 'chat', text: message.trim() })) setMessage(''); setSending(false); };
  return <View style={s.wrap}><View style={s.tabs}>{['text', 'voice'].map(t => <Pressable testID={`chat-${t}-tab`} key={t} onPress={() => setTab(t)} style={[s.tab, tab === t && s.active]}><Ionicons name={t === 'text' ? 'chatbubble-outline' : 'mic-outline'} size={16} color={tab === t ? c.brand : c.muted} /><Text style={[s.tabText, tab === t && { color: c.brand }]}>{t === 'text' ? 'TEXT CHAT' : 'VOICE · RECOMMENDED'}</Text></Pressable>)}</View>
    {tab === 'voice' ? <Voice code={room.code} /> : <><ScrollView ref={scroll} style={s.messages} contentContainerStyle={s.messagesContent} onContentSizeChange={() => scroll.current?.scrollToEnd({ animated: true })} keyboardShouldPersistTaps="handled">{room.chat.length === 0 ? <View style={s.empty}><Ionicons name="chatbubbles-outline" color={c.brand} size={30} /><Body muted>The strategy starts here.</Body><Notice text="Discuss plans, coordinate moves, and ask your King for support. Only your alliance can read these messages." /></View> : room.chat.map(m => <View testID={`chat-message-${m.id}`} key={m.id} style={[s.message, m.user_id === user?.id && s.own]}><View style={s.messageHead}><Label>{m.name}{m.role ? ` · ${m.role.toUpperCase()}` : ''}</Label><Text style={s.time}>{new Date(m.at * 1000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text></View><Text style={s.text}>{m.text}</Text></View>)}</ScrollView><View style={s.compose}><TextInput testID="chat-message-input" accessibilityLabel="Team message" style={s.input} value={message} onChangeText={setMessage} placeholder="Message your alliance…" placeholderTextColor={c.muted} maxLength={500} onSubmitEditing={send} returnKeyType="send" /><Pressable testID="send-chat-button" accessibilityLabel="Send message" disabled={sending || !message.trim()} style={[s.send, (!message.trim() || sending) && s.disabled]} onPress={send}><Ionicons name="arrow-up" size={23} color={c.onBrandPrimary} /></Pressable></View></>}
  </View>;
}
const useStyles = makeStyles(c => ({ wrap: { gap: 16 }, tabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: c.border }, tab: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6, borderBottomWidth: 2, borderBottomColor: c.transparent }, active: { borderBottomColor: c.brand }, tabText: { color: c.muted, fontFamily: 'Manrope', fontSize: 8, letterSpacing: 0.5, fontWeight: '700' }, messages: { height: 280 }, messagesContent: { gap: 12, paddingVertical: 8 }, empty: { gap: 16, paddingTop: 25 }, message: { backgroundColor: c.surfaceSecondary, borderRadius: 10, padding: 13, gap: 7, marginRight: 18 }, own: { backgroundColor: c.brandTertiary, marginRight: 0, marginLeft: 18 }, messageHead: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 7 }, time: { fontFamily: 'Manrope', color: c.muted, fontSize: 8 }, text: { fontFamily: 'Manrope', color: c.onSurface, fontSize: 13, lineHeight: 21 }, compose: { flexDirection: 'row', gap: 10, alignItems: 'center', borderTopWidth: 1, borderTopColor: c.border, paddingTop: 14 }, input: { flex: 1, minWidth: 0, height: 48, borderWidth: 1, borderColor: c.border, borderRadius: 8, paddingHorizontal: 12, fontFamily: 'Manrope', color: c.onSurface, fontSize: 13 }, send: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', backgroundColor: c.brandPrimary, borderRadius: 8 }, disabled: { opacity: 0.4 } }));