import React, { useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import { Share } from 'react-native';
import { Button, Body, Label, Notice, Sheet } from './ui';
import { Piece } from './Piece';
import { ROLES, Role, Room, ROLE_DETAILS, DIFFICULTIES } from '@/src/types';
import { makeStyles, useTheme } from '@/src/theme';
import { useApp } from '@/src/context';

export type RoomAction = (data: Record<string, unknown>) => Promise<boolean>;
export function Lobby({ room, act, busy, onChat }: { room: Room; act: RoomAction; busy: boolean; onChat: () => void }) {
  const s = useStyles(), { colors: c } = useTheme(), { user, notify } = useApp();
  const [select, setSelect] = useState<Role | null>(null), [difficulty, setDifficulty] = useState(false);
  const me = Object.values(room.players).find(p => p?.id === user?.id), filled = Object.keys(room.players).length, ready = Object.values(room.players).filter(p => p?.ready).length;
  return <View style={s.flex}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><View style={s.banner}><View><Label>YOUR PRIVATE INVITATION</Label><Pressable testID="copy-room-code-button" onPress={async () => { await Clipboard.setStringAsync(room.code); notify('Room code copied. Share it with your five allies.'); }} style={s.codeRow}><Text testID="lobby-room-code" style={s.code}>{room.code}</Text><Ionicons name="copy-outline" size={18} color={c.brand} /></Pressable></View><Pressable testID="share-room-button" accessibilityLabel="Share room code" style={s.share} onPress={async () => { try { await Share.share({ message: `Join my WAR CHESS alliance. Room code: ${room.code}. Six commanders. One kingdom.` }); } catch { notify('Copy the room code to invite your team.'); } }}><Ionicons name="share-outline" size={21} color={c.brand} /></Pressable></View>
    <View style={s.heading}><Text style={s.title}>Choose your command.</Text><Body muted>One player. One role. A shared destiny.</Body></View><View style={s.section}><Label>THE ALLIANCE</Label><Text testID="roles-filled-count" style={s.count}>{filled} / 6 ROLES FILLED</Text></View>
    <View style={s.grid}>{ROLES.map(role => { const p = room.players[role], own = p?.id === user?.id; return <Pressable testID={`select-role-${role}`} key={role} disabled={!!p || !!me || busy} onPress={() => setSelect(role)} style={({ pressed }) => [s.roleCard, own && s.ownCard, pressed && s.pressed]}><View style={s.roleTop}><Piece role={role} size={51} />{p ? <Ionicons name={p.ready ? 'checkmark-circle' : 'lock-closed-outline'} size={16} color={p.ready ? c.success : c.brand} /> : <View style={s.availableDot} />}</View><Text style={s.roleTitle}>{ROLE_DETAILS[role].title}</Text><Text style={s.roleTag}>{ROLE_DETAILS[role].subtitle}</Text><View style={s.roleBottom}>{p ? <><View style={[s.connectionDot, { backgroundColor: p.connected ? c.success : c.muted }]} /><Text numberOfLines={1} style={s.playerName}>{own ? `${p.name} · YOU` : p.name}</Text></> : <Text style={s.available}>Available</Text>}</View>{p && <Text testID={`role-${role}-status`} style={[s.readyText, p.ready && { color: c.success }]}>{p.state === 'left' ? 'LEFT · LOCKED' : p.ready ? 'READY FOR BATTLE' : p.connected ? 'CONNECTED · NOT READY' : 'RECONNECTING'}</Text>}</Pressable>; })}</View>
    <Pressable testID="lobby-difficulty-button" disabled={room.host_id !== user?.id} onPress={() => setDifficulty(true)} style={s.difficulty}><View><Label>YOUR ADVERSARY</Label><Text style={s.difficultyName}>Stockfish · {DIFFICULTIES.find(d => d.id === room.difficulty)?.name}</Text></View>{room.host_id === user?.id && <Ionicons name="chevron-forward" size={17} color={c.brand} />}</Pressable>
    <Notice icon="shield-checkmark-outline" text="Roles lock on selection. The match starts automatically when all six roles are filled and every commander is ready." />
    <Button testID="lobby-chat-button" title="TEAM COMMUNICATIONS" variant="secondary" icon="chatbubbles-outline" onPress={onChat} />
  </ScrollView><View style={s.footer}><View style={s.section}><Text style={s.waiting}>{ready === 6 ? 'PREPARING BATTLE' : 'WAITING FOR THE ALLIANCE'}</Text><Text style={s.count}>{ready} / 6 READY</Text></View><Button testID="ready-button" title={me?.ready ? 'READY · TAP TO CANCEL' : me ? 'I AM READY' : 'CHOOSE A ROLE TO READY UP'} disabled={!me || me.state === 'left'} loading={busy} icon={me?.ready ? 'checkmark-circle-outline' : 'shield-outline'} onPress={() => act({ type: 'ready', ready: !me?.ready })} /></View>
    <Sheet visible={!!select} title={select ? `Command the ${ROLE_DETAILS[select].title}` : ''} onClose={() => setSelect(null)}>{select && <><View style={s.selectionPiece}><Piece role={select} size={110} /></View><Label>{ROLE_DETAILS[select].subtitle}</Label><Body>{ROLE_DETAILS[select].description}</Body><Notice icon="lock-closed-outline" text="This decision is permanent for the current match. You cannot switch to another role." /><Button testID="confirm-role-button" title={`LOCK IN ${select.toUpperCase()}`} loading={busy} onPress={async () => { if (await act({ type: 'role', role: select })) setSelect(null); }} /></>}</Sheet>
    <Sheet visible={difficulty} title="Choose your adversary" onClose={() => setDifficulty(false)}>{DIFFICULTIES.map(d => <Button key={d.id} testID={`lobby-difficulty-${d.id}`} title={d.name.toUpperCase()} variant={room.difficulty === d.id ? 'primary' : 'secondary'} onPress={async () => { if (await act({ type: 'difficulty', difficulty: d.id })) setDifficulty(false); }} />)}</Sheet>
  </View>;
}
const useStyles = makeStyles(c => ({ flex: { flex: 1 }, content: { padding: 24, gap: 22, width: '100%', maxWidth: 760, alignSelf: 'center' }, banner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: c.border, borderRadius: 10, backgroundColor: c.surfaceSecondary, padding: 18 }, codeRow: { flexDirection: 'row', alignItems: 'center', gap: 14, minHeight: 44 }, code: { fontFamily: 'Cinzel', fontSize: 28, letterSpacing: 4, color: c.onSurface }, share: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center', borderLeftWidth: 1, borderLeftColor: c.border }, heading: { gap: 9 }, title: { fontFamily: 'Cinzel', fontSize: 26, lineHeight: 35, color: c.onSurface }, section: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, count: { fontFamily: 'Manrope', fontSize: 9, letterSpacing: 1, color: c.muted }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, roleCard: { width: '48%', flexGrow: 1, backgroundColor: c.surfaceSecondary, padding: 15, borderWidth: 1, borderColor: c.border, borderRadius: 10, minHeight: 164 }, ownCard: { backgroundColor: c.brandTertiary, borderColor: c.brand }, roleTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' }, availableDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: c.success, marginTop: 8 }, roleTitle: { fontFamily: 'Cinzel', fontSize: 21, color: c.onSurface, marginTop: 5 }, roleTag: { fontFamily: 'Manrope', color: c.muted, letterSpacing: 1.5, fontSize: 7, marginTop: 5 }, roleBottom: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 14 }, connectionDot: { width: 5, height: 5, borderRadius: 3 }, playerName: { fontFamily: 'Manrope', color: c.onSurface, fontSize: 10, flex: 1 }, available: { fontFamily: 'Manrope', color: c.brand, fontSize: 11 }, readyText: { fontSize: 6.5, fontFamily: 'Manrope', color: c.muted, letterSpacing: 0.5, marginTop: 7 }, difficulty: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 18, backgroundColor: c.surfaceSecondary, borderWidth: 1, borderColor: c.border, borderRadius: 10 }, difficultyName: { fontFamily: 'Manrope', color: c.onSurface, fontSize: 13, marginTop: 8 }, footer: { paddingHorizontal: 24, paddingTop: 14, paddingBottom: 14, gap: 12, borderTopWidth: 1, borderTopColor: c.border, backgroundColor: c.surface }, waiting: { color: c.brand, fontFamily: 'Manrope', fontSize: 8, letterSpacing: 1.3 }, selectionPiece: { alignItems: 'center', paddingVertical: 10 }, pressed: { opacity: 0.75 } }));