import React, { useState } from 'react';
import { ScrollView, Text, View } from 'react-native';
import { Screen, Title, Body, Label, Card, Chips, Notice } from '@/src/components/ui';
import { Piece } from '@/src/components/Piece';
import { makeStyles } from '@/src/theme';
import { ROLES, ROLE_DETAILS } from '@/src/types';

const chapters = [
  { title: 'Six minds. One side.', body: 'Six human commanders play the white pieces against Stockfish. Each player chooses exactly one role and controls every piece assigned to it. A role locks immediately. All six roles must be filled and everyone must ready up before the server starts the match.' },
  { title: 'One minute to strategize.', body: 'Before every human-team turn, you have 60 seconds to discuss and make a move. Any authorized move ends the team turn. Only one move is played before the AI responds. Text chat is always available; live voice is recommended when configured.' },
  { title: 'The King’s command.', body: 'Select a piece, then a legal square. Actions that require approval are sent to the King. Approval executes the move; rejection lets you choose again. An unanswered timer gives the King control of any legal piece. The fourth forced command defeats the entire team.' },
  { title: 'Fall. Watch. Return.', body: 'Losing all pieces you own eliminates you. Choose to spectate to remain eligible for revival. After a pawn promotes, Pawn keeps ownership by default. If the original role is eliminated and spectating, Pawn may transfer the promoted piece and revive that commander. Players who leave cannot return through promotion.' },
  { title: 'No ordinary endings.', body: 'Checkmate ends the match; kings are never captured under legal chess rules. Repetition, insufficient material, and move-count draws do not end War Chess. In stalemate, the match stays open without a strategy timer. Four of the six commanders must vote yes to restart.' },
];
export default function Guide() {
  const [tab, setTab] = useState('essentials'), s = useStyles();
  return <Screen title="How to play?" eyebrow="THE FIELD MANUAL" scroll={false}><Chips items={[{ id: 'essentials', label: 'The essentials' }, { id: 'roles', label: 'Roles & permissions' }, { id: 'special', label: 'Special moves' }]} selected={tab} onSelect={setTab} /><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.intro}><Label>STRONGER TOGETHER</Label><Title>{tab === 'roles' ? 'Know your command.' : tab === 'special' ? 'Master the board.' : 'An alliance, not an army.'}</Title></View>
    {tab === 'essentials' ? chapters.map((chapter, i) => <View key={chapter.title} style={s.chapter}><Text style={s.number}>0{i + 1}</Text><View style={s.chapterBody}><Text style={s.chapterTitle}>{chapter.title}</Text><Body muted>{chapter.body}</Body></View></View>) : tab === 'roles' ? ROLES.map(role => <Card key={role}><View style={s.roleTitle}><Piece role={role} size={46} /><View><Label>{ROLE_DETAILS[role].subtitle}</Label><Text style={s.chapterTitle}>{ROLE_DETAILS[role].title}</Text></View></View><Body muted>{role === 'king' ? 'Move the King freely. Approve or reject teammates’ restricted actions. After strategy time expires, command any piece. A fourth forced takeover loses the match.' : role === 'queen' ? 'Move freely to empty squares. Every capture requires the King’s approval.' : role === 'pawn' ? 'Move and capture freely for the entire match. Promoted pieces remain yours unless you choose to revive a spectating commander. Your moves never need approval.' : 'Move and capture freely during the first FOUR human-team turns. After that, both moves and captures need approval. If one of your pieces is captured, the lone survivor moves freely again, but captures still need approval.'}</Body></Card>) : <><Card><Text style={s.chapterTitle}>Castling</Text><Body muted>The King initiates castling as a normal legal King move. The rook travels with it, while ownership stays with Rook. You cannot castle from, through, or into check.</Body></Card><Card><Text style={s.chapterTitle}>En passant</Text><Body muted>A pawn may capture an adjacent pawn that just advanced two squares, on the immediately following turn. The server checks this automatically.</Body></Card><Card><Text style={s.chapterTitle}>Pawn promotion</Text><Body muted>Choose Queen, Rook, Bishop, or Knight on reaching the final rank. You then have 30 seconds to transfer control to an eligible spectating commander, or keep it. No answer defaults to keeping the piece.</Body></Card><Card><Text style={s.chapterTitle}>Check & checkmate</Text><Body muted>Only legal moves that resolve check are allowed. If no legal response exists while in check, that side loses. Pieces cannot expose their own King to check.</Body></Card></>}
    <Notice text="Opening freedom counts four human-team turns — AI moves do not count." />
  </ScrollView></Screen>;
}
const useStyles = makeStyles(c => ({ content: { padding: 24, gap: 26, maxWidth: 760, alignSelf: 'center', width: '100%' }, intro: { gap: 10, marginBottom: 8 }, chapter: { flexDirection: 'row', gap: 16 }, number: { fontFamily: 'Cinzel', color: c.brand, fontSize: 23, width: 35 }, chapterBody: { flex: 1, gap: 10 }, chapterTitle: { fontFamily: 'Cinzel', fontSize: 19, lineHeight: 28, color: c.onSurface }, roleTitle: { flexDirection: 'row', alignItems: 'center', gap: 14 } }));