import React from 'react';
import { Image, Pressable, ScrollView, Text, View, useWindowDimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { useApp } from '@/src/context';
import { makeStyles, useTheme } from '@/src/theme';

const HERO = 'https://static.prod-images.emergentagent.com/jobs/722c2ae4-cbcc-441c-9aa1-bedae7716acf/images/f7a0a5dc84e0c50f0f626e9a5858dc4db763856725cca8bbb798969a10ef712b.jpeg';
export default function Home() {
  const s = useStyles(), { colors: c } = useTheme(), { user, loading } = useApp(), { width } = useWindowDimensions();
  const wide = width > 850;
  return <SafeAreaView style={s.screen} edges={['top', 'bottom']}><View style={s.header}>
    <View style={s.brand}><MaterialCommunityIcons name="chess-king" size={27} color={c.brand} /><Text style={s.brandText}>WAR CHESS</Text></View>
    <View style={s.tools}><Pressable testID="leaderboards-button" accessibilityLabel="Role leaderboards" style={s.tool} onPress={() => router.push('/leaderboards')}><Ionicons name="trophy-outline" size={19} color={c.brand} /></Pressable><Pressable testID="account-button" accessibilityLabel="Your account" style={s.avatar} onPress={() => router.push(user ? '/settings' : '/auth')}><Text style={s.avatarText}>{user ? user.name.slice(0, 1).toUpperCase() : 'W'}</Text></Pressable></View>
  </View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[s.body, wide && s.wideBody]}>
    <Animated.View entering={FadeInDown.duration(700)} style={[s.hero, wide && s.wideHero]} testID="home-hero">
      <Image source={{ uri: HERO }} style={[s.heroImage, !wide && s.mobileHeroImage]} resizeMode={wide ? 'cover' : 'contain'} />
      <LinearGradient colors={[c.heroBackground, c.heroFade, c.heroFade, c.heroBackground]} locations={[0, 0.25, 0.73, 1]} style={s.heroOverlay} />
      <View style={s.heroText}><View style={s.eyebrowRow}><View style={s.goldLine} /><Text style={s.eyebrow}>THE ART OF ALLIANCE</Text><View style={s.goldLine} /></View><Text style={s.war}>WAR<Text style={s.chess}>{'\n'}CHESS</Text></Text><Text style={s.tagline}>Six commanders. One kingdom.</Text></View>
      <View style={s.heroFoot}><View style={s.dot} /><Text style={s.heroFootText}>COOPERATIVE CHESS. REIMAGINED.</Text></View>
    </Animated.View>
    <Animated.View entering={FadeInDown.delay(160).duration(700)} style={[s.menu, wide && s.wideMenu]}>
      {wide && <View style={s.desktopIntro}><Text style={s.desktopTitle}>A kingdom is never{ '\n' }won alone.</Text><Text style={s.description}>Choose your role. Rally your allies. Face the engine.</Text></View>}
      <Pressable testID="join-game-button" disabled={loading} onPress={() => router.push(user ? '/join' : '/auth')} style={({ pressed }) => [s.join, pressed && s.pressed]}><MaterialCommunityIcons name="sword-cross" size={24} color={c.onBrandPrimary} /><Text style={s.joinText}>JOIN GAME</Text><Ionicons name="arrow-forward" size={21} color={c.onBrandPrimary} /></Pressable>
      <Pressable testID="how-to-play-button" onPress={() => router.push('/guide')} style={({ pressed }) => [s.menuButton, pressed && s.pressed]}><Ionicons name="book-outline" size={20} color={c.brand} /><Text style={s.menuText}>HOW TO PLAY?</Text><Ionicons name="chevron-forward" size={17} color={c.muted} /></Pressable>
      <Pressable testID="settings-button" onPress={() => router.push('/settings')} style={({ pressed }) => [s.menuButton, pressed && s.pressed]}><Ionicons name="options-outline" size={21} color={c.brand} /><Text style={s.menuText}>SETTINGS</Text><Ionicons name="chevron-forward" size={17} color={c.muted} /></Pressable>
      <View style={s.footer}><View style={s.footerLine} /><Ionicons name="people-outline" size={15} color={c.muted} /><Text style={s.footerText}>6 PLAYERS</Text><Text style={s.footerVs}>VS</Text><MaterialCommunityIcons name="chess-knight" size={17} color={c.muted} /><Text style={s.footerText}>1 ENGINE</Text><View style={s.footerLine} /></View>
      <Text style={s.bottomText}>STRATEGY IS POWER. UNITY IS VICTORY.</Text>
    </Animated.View>
  </ScrollView></SafeAreaView>;
}
const useStyles = makeStyles(c => ({ screen: { flex: 1, backgroundColor: c.surface }, header: { height: 72, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: c.divider }, brand: { flexDirection: 'row', gap: 9, alignItems: 'center' }, brandText: { fontFamily: 'Cinzel', fontSize: 15, letterSpacing: 2.3, color: c.onSurface }, tools: { flexDirection: 'row', gap: 12, alignItems: 'center' }, tool: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, avatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: c.brandTertiary, borderColor: c.borderStrong, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontFamily: 'Cinzel', color: c.brand, fontSize: 15 },
  body: { flexGrow: 1, paddingBottom: 20, maxWidth: 1320, width: '100%', alignSelf: 'center' }, wideBody: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 60, gap: 64 }, hero: { height: 435, overflow: 'hidden', backgroundColor: c.heroBackground }, wideHero: { flex: 1, height: 670, borderRadius: 12 }, heroImage: { position: 'absolute', width: '100%', height: '127%', top: -35 }, heroOverlay: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0 }, heroText: { alignItems: 'center', paddingTop: 27 }, eyebrowRow: { flexDirection: 'row', alignItems: 'center', gap: 13 }, goldLine: { width: 23, height: 1, backgroundColor: c.brand }, eyebrow: { fontFamily: 'Manrope', fontSize: 8.5, letterSpacing: 3, color: c.pieceMid, fontWeight: '700' }, war: { fontFamily: 'Cinzel', fontSize: 60, lineHeight: 62, color: c.heroText, letterSpacing: 11, textAlign: 'center', marginTop: 16, paddingLeft: 11 }, chess: { fontSize: 52, letterSpacing: 7 }, tagline: { color: c.heroMuted, fontSize: 12, fontFamily: 'Manrope', letterSpacing: 0.8, marginTop: 13 }, heroFoot: { position: 'absolute', bottom: 17, left: 0, right: 0, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, dot: { width: 4, height: 4, backgroundColor: c.brand, borderRadius: 2 }, heroFootText: { fontFamily: 'Manrope', fontSize: 8, letterSpacing: 2.2, color: c.heroMuted },
  mobileHeroImage: { top: 72, height: '95%' }, menu: { paddingHorizontal: 26, gap: 12, paddingTop: 12 }, wideMenu: { width: 360, paddingHorizontal: 0 }, join: { height: 60, borderRadius: 7, backgroundColor: c.brandPrimary, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 22, gap: 17 }, joinText: { flex: 1, fontFamily: 'Manrope', fontWeight: '800', fontSize: 13, letterSpacing: 2.6, color: c.onBrandPrimary }, menuButton: { height: 56, borderRadius: 7, borderWidth: 1, borderColor: c.border, backgroundColor: c.surfaceSecondary, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 22, gap: 17 }, menuText: { flex: 1, fontFamily: 'Manrope', fontSize: 11, fontWeight: '700', letterSpacing: 2, color: c.onSurfaceSecondary }, pressed: { opacity: 0.75, transform: [{ scale: 0.98 }] }, footer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, marginTop: 17 }, footerText: { fontSize: 8, fontFamily: 'Manrope', color: c.muted, letterSpacing: 1.2 }, footerVs: { fontSize: 8, fontFamily: 'Manrope', color: c.brand, paddingHorizontal: 5 }, footerLine: { flex: 1, height: 1, backgroundColor: c.border }, bottomText: { fontSize: 7, letterSpacing: 2.1, color: c.muted, fontFamily: 'Manrope', textAlign: 'center', marginTop: 5 }, desktopIntro: { gap: 14, marginBottom: 30 }, desktopTitle: { fontFamily: 'Cinzel', fontSize: 31, lineHeight: 44, color: c.onSurface }, description: { fontFamily: 'Manrope', fontSize: 14, color: c.muted, lineHeight: 24 },
}));