import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, Text, View, TextInput } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Screen, Button, Title, Body, Label, Card, Sheet, Notice } from '@/src/components/ui';
import { Piece } from '@/src/components/Piece';
import { makeStyles, useTheme } from '@/src/theme';
import { useApp } from '@/src/context';
import { api } from '@/src/api';
import { DIFFICULTIES, ROLES } from '@/src/types';

export default function Join() {
  const s = useStyles(), { colors: c } = useTheme(), { user, loading, notify } = useApp();
  const [rooms, setRooms] = useState<any[]>([]), [fetching, setFetching] = useState(true), [code, setCode] = useState(''), [busy, setBusy] = useState(false), [create, setCreate] = useState(false), [difficulty, setDifficulty] = useState('easy'), [error, setError] = useState('');
  const refresh = useCallback(async () => { try { setRooms(await api('/rooms')); setError(''); } catch (e: any) { setError(e.message); } finally { setFetching(false); } }, []);
  useEffect(() => { if (loading) return; if (!user) { router.replace('/auth'); return; } refresh(); const t = setInterval(refresh, 10000); return () => clearInterval(t); }, [user, loading, refresh]);
  const enter = async (roomCode: string) => { if (roomCode.length !== 6) { notify('Enter the six-letter room code.'); return; } setBusy(true); try { const room = await api(`/rooms/${roomCode.toUpperCase()}/enter`, 'POST'); router.push({ pathname: '/room/[code]', params: { code: room.code } }); } catch (e: any) { notify(e.message); } finally { setBusy(false); } };
  const createRoom = async () => { setBusy(true); try { const room = await api('/rooms', 'POST', { difficulty }); setCreate(false); router.push({ pathname: '/room/[code]', params: { code: room.code } }); } catch (e: any) { notify(e.message); } finally { setBusy(false); } };
  return <Screen title="Join the alliance" eyebrow="WAR CHESS" right={<Pressable testID="refresh-rooms-button" accessibilityLabel="Refresh rooms" style={s.iconButton} onPress={refresh}><Ionicons name="refresh" size={21} color={c.brand} /></Pressable>}>
    <View style={s.intro}><Label>EVERY ROLE MATTERS</Label><Title>Find your war room.</Title><Body muted>Bring your allies or join a waiting team. Six roles must unite before battle begins.</Body></View>
    <Card><Label>HAVE AN INVITATION?</Label><View style={s.codeRow}><TextInput testID="room-code-input" accessibilityLabel="Room code" placeholder="ROOM CODE" placeholderTextColor={c.muted} value={code} onChangeText={v => setCode(v.toUpperCase().replace(/[^A-Z]/g, ''))} autoCapitalize="characters" maxLength={6} style={s.codeInput} onSubmitEditing={() => enter(code)} /><Pressable testID="join-code-button" accessibilityLabel="Join room using code" disabled={busy} style={s.go} onPress={() => enter(code)}>{busy ? <ActivityIndicator color={c.onBrandPrimary} /> : <Ionicons name="arrow-forward" size={23} color={c.onBrandPrimary} />}</Pressable></View></Card>
    <Button testID="create-room-button" title="CREATE A WAR ROOM" icon="add" onPress={() => setCreate(true)} />
    <View style={s.section}><Label>OPEN WAR ROOMS</Label><Text testID="room-count" style={s.count}>{rooms.length} AVAILABLE</Text></View>
    {error ? <Notice text={error} /> : fetching ? <ActivityIndicator color={c.brand} /> : rooms.length === 0 ? <Card><View style={s.emptyIcon}><Ionicons name="bonfire-outline" size={30} color={c.brand} /></View><Body>No alliances waiting. Start your own.</Body><Body muted>Create a room and share its code with five other commanders.</Body></Card> : rooms.map(room => <Pressable testID={`room-${room.code}`} key={room.code} onPress={() => enter(room.code)} disabled={!room.joinable || busy} style={({ pressed }) => [s.room, pressed && s.pressed]}><View style={s.section}><Text style={s.roomTitle}>{room.host}’s alliance</Text><Ionicons name="arrow-up-right-box" size={19} color={c.brand} /></View><Text style={s.roomMeta}>{room.code}  /  {DIFFICULTIES.find(d => d.id === room.difficulty)?.name.toUpperCase()}</Text><View style={s.roleRow}>{ROLES.map(role => <View key={role} style={[s.roleSlot, room.roles.includes(role) && s.roleFilled]}><Piece role={role} size={29} /></View>)}<Text style={s.filled}>{room.filled}<Text style={s.total}> / 6</Text></Text></View></Pressable>)}
    <Notice icon="lock-closed-outline" text="One commander, one role. Once selected, your role is locked for the match." />
    <Sheet visible={create} title="Forge an alliance" onClose={() => setCreate(false)}><Body muted>Choose your opponent’s strength. Invite five allies and ready up together.</Body><Label>ENGINE DIFFICULTY</Label>{DIFFICULTIES.map(d => <Pressable testID={`difficulty-${d.id}`} key={d.id} onPress={() => setDifficulty(d.id)} style={[s.difficulty, difficulty === d.id && s.selected]}><View style={s.difficultyText}><Text style={s.difficultyTitle}>{d.name}</Text><Text style={s.difficultyDescription}>{d.description}</Text></View><View style={s.bars}>{[1, 2, 3, 4].map(n => <View key={n} style={[s.bar, { height: 8 + n * 5 }, n <= d.level && s.barActive]} />)}</View></Pressable>)}<Button testID="confirm-create-room-button" title="OPEN WAR ROOM" onPress={createRoom} loading={busy} icon="arrow-forward" /></Sheet>
  </Screen>;
}
const useStyles = makeStyles(c => ({ intro: { gap: 10, paddingTop: 10 }, iconButton: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center' }, codeRow: { flexDirection: 'row', gap: 12 }, codeInput: { flex: 1, minWidth: 0, height: 52, fontFamily: 'Manrope', fontSize: 17, letterSpacing: 3, color: c.onSurface, borderBottomWidth: 1, borderBottomColor: c.border }, go: { width: 52, height: 52, borderRadius: 7, alignItems: 'center', justifyContent: 'center', backgroundColor: c.brandPrimary }, section: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, count: { color: c.muted, fontSize: 9, letterSpacing: 1, fontFamily: 'Manrope' }, emptyIcon: { marginBottom: 6 }, room: { backgroundColor: c.surfaceSecondary, borderWidth: 1, borderColor: c.border, borderRadius: 12, padding: 20, gap: 14 }, roomTitle: { fontFamily: 'Cinzel', fontSize: 17, color: c.onSurface, flex: 1 }, roomMeta: { fontFamily: 'Manrope', fontSize: 9, color: c.muted, letterSpacing: 1.6 }, roleRow: { flexDirection: 'row', alignItems: 'center', gap: 5 }, roleSlot: { width: 31, height: 36, alignItems: 'center', justifyContent: 'center', opacity: 0.35 }, roleFilled: { backgroundColor: c.brandTertiary, borderRadius: 4, opacity: 1 }, filled: { fontFamily: 'Cinzel', color: c.brand, fontSize: 21, marginLeft: 'auto' }, total: { color: c.muted, fontSize: 14 }, pressed: { opacity: 0.7 }, difficulty: { borderWidth: 1, borderColor: c.border, borderRadius: 10, padding: 15, flexDirection: 'row', gap: 12, alignItems: 'center' }, selected: { borderColor: c.brand, backgroundColor: c.brandTertiary }, difficultyText: { flex: 1, gap: 6 }, difficultyTitle: { fontFamily: 'Cinzel', fontSize: 18, color: c.onSurface }, difficultyDescription: { fontFamily: 'Manrope', fontSize: 12, lineHeight: 19, color: c.muted }, bars: { flexDirection: 'row', alignItems: 'flex-end', gap: 3 }, bar: { width: 4, backgroundColor: c.border, borderRadius: 2 }, barActive: { backgroundColor: c.brand } }));