import React from 'react';
import { Pressable, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import Slider from '@react-native-community/slider';
import { Screen, Title, Body, Label, Card, Button } from '@/src/components/ui';
import { useApp } from '@/src/context';
import { makeStyles, setColorScheme, useTheme } from '@/src/theme';
import { useSound } from '@/src/sound';

export default function Settings() {
  const s = useStyles(), { scheme, colors: c } = useTheme(), { user, volume, setVolume, signOut, notify } = useApp(), sound = useSound();
  return <Screen title="Settings" eyebrow="MAKE IT YOURS"><View style={s.intro}><Title>Your game. Your world.</Title><Body muted>A few refinements for the way you play.</Body></View><Label>APPEARANCE</Label><View style={s.themes}>{(['dark', 'light'] as const).map(theme => <Pressable testID={`theme-${theme}-button`} key={theme} onPress={() => setColorScheme(theme)} style={[s.theme, scheme === theme && s.selected]}><View style={[s.preview, theme === 'light' ? s.lightPreview : s.darkPreview]}><View style={[s.previewLine, theme === 'light' ? s.lightLine : s.darkLine]} /><View style={[s.previewBlock, theme === 'light' ? s.lightLine : s.darkLine]} /></View><View style={s.themeLabel}><Text style={s.themeText}>{theme === 'dark' ? 'Dark mode' : 'Light mode'}</Text><Ionicons name={scheme === theme ? 'checkmark-circle' : 'ellipse-outline'} size={18} color={scheme === theme ? c.brand : c.muted} /></View><Text style={s.themeSub}>{theme === 'dark' ? 'Obsidian & gold' : 'Ivory & sky'}</Text></Pressable>)}</View><Body muted>Your theme follows you everywhere, from the war room to the board.</Body><Label>AUDIO</Label><Card><View style={s.row}><Ionicons name={volume === 0 ? 'volume-mute-outline' : 'volume-medium-outline'} size={23} color={c.brand} /><Text style={s.settingTitle}>Sound effects</Text><Text testID="volume-value" style={s.volume}>{Math.round(volume * 100)}%</Text></View><Slider testID="sound-volume-slider" accessibilityLabel="Sound effects volume" minimumValue={0} maximumValue={1} step={0.05} value={volume} onValueChange={setVolume} onSlidingComplete={() => sound('move')} minimumTrackTintColor={c.brand} maximumTrackTintColor={c.border} thumbTintColor={c.brandPrimary} /><Body muted>Piece movement, captures, commands, and elimination announcements.</Body><Button testID="preview-sound-button" title="PREVIEW SOUND" variant="ghost" compact icon="play-outline" onPress={() => sound('move')} /></Card>
    <Label>ACCOUNT</Label><Card>{user ? <><Text style={s.settingTitle}>{user.name}</Text><Body muted>{user.email}</Body><Button testID="sign-out-button" title="SIGN OUT" variant="secondary" onPress={async () => { try { await signOut(); router.replace('/'); } catch (e: any) { notify(e.message); } }} /></> : <><Body muted>Sign in to join an alliance and build your role legacy.</Body><Button testID="settings-sign-in-button" title="SIGN IN" variant="secondary" onPress={() => router.push('/auth')} /></>}</Card><Text style={s.version}>WAR CHESS  /  v1.0.0{ '\n' }Powered by Stockfish · GPL-3.0</Text></Screen>;
}
const useStyles = makeStyles(c => ({ intro: { gap: 10, paddingTop: 8 }, themes: { flexDirection: 'row', gap: 12 }, theme: { flex: 1, borderWidth: 1, borderColor: c.border, borderRadius: 12, padding: 12, gap: 10 }, selected: { borderColor: c.brand, backgroundColor: c.brandTertiary }, preview: { height: 82, borderRadius: 7, padding: 15, gap: 12 }, darkPreview: { backgroundColor: '#111713' }, lightPreview: { backgroundColor: '#EAF3F8' }, darkLine: { backgroundColor: '#CDB078' }, lightLine: { backgroundColor: '#94C2DF' }, previewLine: { height: 5, width: '45%', borderRadius: 2 }, previewBlock: { height: 23, width: '100%', borderRadius: 3, opacity: 0.5 }, themeLabel: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, themeText: { fontFamily: 'Manrope', fontSize: 12, color: c.onSurface, fontWeight: '700' }, themeSub: { fontFamily: 'Manrope', fontSize: 10, color: c.muted }, row: { flexDirection: 'row', alignItems: 'center', gap: 12 }, settingTitle: { fontFamily: 'Manrope', fontSize: 15, color: c.onSurface, flex: 1, fontWeight: '600' }, volume: { fontFamily: 'Manrope', fontSize: 12, color: c.brand }, version: { color: c.muted, fontFamily: 'Manrope', textAlign: 'center', fontSize: 9, lineHeight: 20, letterSpacing: 1.2 } }));